version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - ./db/migration:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
